# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=250)),
                ('picture', models.ImageField(upload_to='/stores/')),
                ('store_type', models.CharField(choices=[('education', 'Education'), ('fashion', 'Fashion'), ('food', 'Food'), ('furniture', 'Furniture'), ('electronics', 'Electronics'), ('beauty', 'Beauty'), ('', 'No category set')], max_length=25)),
            ],
        ),
    ]
