# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='picture',
            field=models.ImageField(upload_to='stores/'),
        ),
    ]
