# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20160729_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('education', 'Education'), ('fashion', 'Fashion'), ('food', 'Food'), ('furniture', 'Furniture'), ('electronics', 'Electronics'), ('beauty', 'Beauty'), ('', 'No category set')], max_length=25),
        ),
    ]
