# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20160729_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='picture',
            field=models.ImageField(default='img/nopic.png', upload_to='stores/'),
        ),
    ]
