# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20160729_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='picture',
            field=models.ImageField(upload_to='stores/'),
        ),
    ]
